# Generated by Django 3.2 on 2021-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Maharashtra', 'Maharashtra')], max_length=40)),
                ('street_address', models.TextField()),
                ('house_no', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('maritual_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorsed', 'Divorsed'), ('Widowed', 'Widowed')], max_length=10)),
                ('disease_category', models.CharField(choices=[('Topographic', 'Topographic'), ('Anatomic', 'Anatomic'), ('Physiological', 'Physiological'), ('Pathological', 'Pathological'), ('Etiologic', 'Etiologic'), ('Juristic', 'Juristic'), ('Epidemiological', 'Epidemiological'), ('Statistical', 'Statistical'), ('Other', 'Other')], max_length=15)),
                ('problem', models.TextField()),
                ('previous_health_issue', models.TextField()),
                ('date_admitted', models.DateField(auto_now=True)),
            ],
        ),
    ]
