# Generated by Django 3.2 on 2021-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='house_no',
            field=models.CharField(max_length=10),
        ),
    ]
